spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sinfo-test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        jdbc:
          batch_size: 1000


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace